# Generated by Django 5.0.6 on 2024-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_album_song_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='upload',
            new_name='upload_image',
        ),
        migrations.AddField(
            model_name='song',
            name='upload_song',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
