# Generated by Django 5.0.6 on 2024-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_upload_song_upload_image_song_upload_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_song',
            field=models.FileField(default='fallback.png', upload_to='uploads/'),
        ),
    ]
