# Generated by Django 5.0.6 on 2024-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_upload_image_alter_song_upload_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_image',
            field=models.ImageField(default='fallback.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_song',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
