# Generated by Django 5.0.6 on 2024-06-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='playlist_name',
        ),
    ]
