# Generated by Django 5.0.6 on 2024-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_upload_image_alter_song_upload_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
