# Generated by Django 5.0.6 on 2024-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='upload_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_song',
            field=models.FileField(upload_to='media/'),
        ),
    ]
