# Generated by Django 5.0.6 on 2024-06-13 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_upload_image_alter_song_upload_song'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='upload_image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='upload_song',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='https://placehold.co/300x300/png', upload_to='media/songimage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default='', upload_to='media/songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('liked_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_id', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
