# Generated by Django 5.0.6 on 2024-06-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='songs_p',
        ),
    ]
