# Generated by Django 5.0.6 on 2024-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_song_options_remove_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
