# Generated by Django 5.0.6 on 2024-06-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_rename_songs_playlist_songs_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs_p',
            new_name='songs',
        ),
    ]
