# Generated by Django 5.0.6 on 2024-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_song_song_alter_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
