# Generated by Django 5.0.6 on 2024-06-19 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_playlist_image_alter_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='images/music-placeholder.png', upload_to='playlist_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
