# Generated by Django 5.0.6 on 2024-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsong',
            name='liked_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likedsong',
            name='music_id',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
