# Generated by Django 5.0.6 on 2024-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_likedsong_liked_id_alter_likedsong_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsong',
            name='liked_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
