# Generated by Django 5.0.6 on 2024-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedsong',
            old_name='music_id',
            new_name='song',
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default='genre', max_length=20),
        ),
    ]
