# Generated by Django 5.0.6 on 2024-06-21 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_rename_music_id_likedsong_song_alter_song_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedsong',
            name='user',
        ),
        migrations.AddField(
            model_name='likedsong',
            name='user',
            field=models.ManyToManyField(related_name='liked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
